services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
    env_file:
      - ./Backend/.env
    volumes:
      - ./Backend:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: frostedfabrics
      MYSQL_USER: ${dbusername}
      MYSQL_PASSWORD: ${dbpassword}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: